App header component
agnieszkajaskiewicz/PlantManager pull request #40
Opened 2022-04-25 18:16 UTC by agnieszkajaskiewicz

2022-07-08 16:02 UTC, lukjab71 requested changes
Ogólnie nie wygląda to źle, wygląda całkiem dobrze. Główna uwaga to taka że import boostrapa u mnie na komputerze wywala aplikację reactową i wydaje mi się że ten import jest niepotrzebny. 

Jeden problem który na pewno istnieje - z jakiegoś powodu, pomimo poprawnego logoutu i wygaszenia sesji w spring security, i tak mogę się dostać do danych użytkownika. 

Przykład: zaloguj się, wejdź na dashboard, zobacz rośliny użytkownika, kliknij logout. Niby się wylogowało. Następnie poprzez url wejdź na /dashboard i zobacz że backend cały czas zwraca rośliny użytkownika. Wydaje mi się żę to dlatego że mieszamy spring security i  SecurityServiceImpl która stosuje jakąś ręczną obsługę logowania. Muszę się nad tym chwilę zastanowić, a dawno nie widziałem javy ani springa na oczy :P Dlatego to może na razie bym olał, natomiast nie możemy o tym zapomnieć.

2022-07-21 15:28 UTC, agnieszkajaskiewicz commented on plantmanager-react/src/components/Login/Login.js
> +import 'bootstrap/dist/css/bootstrap.min.css';
Usunięte.

2022-07-21 15:28 UTC, agnieszkajaskiewicz commented on plantmanager-react/src/services/AuthService/AuthService.js
> +    logoutUser: () => {
Poprawione.

2022-07-21 15:29 UTC, agnieszkajaskiewicz commented on PlantManager/src/main/java/com/ajaskiewicz/PlantManager/web/rest/UserController.java
> -    @GetMapping("/sign-in") //ten endpoint jest wołany tylko na logout, prawdopodobnie go nie potrzebujemy
Przywrócone :)

2022-07-21 15:29 UTC, agnieszkajaskiewicz commented on PlantManager/src/main/java/com/ajaskiewicz/PlantManager/web/WebSecurityConfig.java
> +                .logoutSuccessHandler((req, res, auth) -> res.setStatus(HttpStatus.OK.value()));
Dodane.

2022-07-21 15:29 UTC, agnieszkajaskiewicz commented on plantmanager-react/src/components/AppHeader/AppHeader.js
> +    var username = localStorage.getItem('username');
Zmienione.

2022-11-24 19:21 UTC, merged